services:
  backend:
    build: .
    container_name: chat-backend
    expose:
      - "8000"
    restart: always
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    container_name: chat-nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: always
    networks:
      - appnet

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: always
    networks:
      - appnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    networks:
      - appnet

networks:
  appnet:
    driver: bridge